language: node_js
sudo: false
node_js:
- '0.10'
after_install:
- gem install compass
- npm install -g bower grunt-cli
before_script:
- bower install
script:
- grunt build
before_deploy:
- tar -cvz -f nndd.tar.gz -C dist nndd
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kbpshxqKM9cQjxIgnvzTFujThaJQ/bgcEreBXfitxBie6NMUY8bge2eHd6kEixotnZ3PfuAuyrrpnw1YNMdNatt1aslV2+oLJQ12L1YGzlnqoHnwyDX96PUzp3sOHtJXcxhNn8jMIoH0Nq7nRzBzDJUuvHyYoQdd9b9OQlC/5oo=
  file: nndd.tar.gz
  on:
    repo: instedd/notifiable-diseases
    tags: true
    all_branches: true
